/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Empresa.gui.Frames;

import Empresa.backend.Entidades.Cliente;
import Empresa.backend.Entidades.Empresa;
import Empresa.backend.Entidades.Habitacion;
import Empresa.backend.Registro.BusquedaDeEmpresas;
import Empresa.backend.Registro.BusquedaDeHabitaciones;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesfrin
 */
public class MenuParaClienteFrame extends javax.swing.JFrame {

    private Cliente clienteActual;
    private ArrayList<Empresa> listaDeHoteles;
    private Empresa hotelSeleccionado;
    private ArrayList<Habitacion> habitacionesDisponibles;
    private ArrayList<Habitacion> habitacionesQueSeReservaran;
    private Integer diasDeAlojamiento;

    /**
     * Creates new form MenuCParaClienteFrame
     *
     * @param clienteActual
     */
    public MenuParaClienteFrame(Cliente clienteActual) {
        this.clienteActual = clienteActual;
        this.listaDeHoteles = new ArrayList<>();
        this.habitacionesDisponibles = new ArrayList<>();
        this.habitacionesQueSeReservaran = new ArrayList<>();
        this.hotelSeleccionado = null;
        this.diasDeAlojamiento = null;
        initComponents();
        buscarHoteles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hotelesDeEmpresaTable = new javax.swing.JTable();
        seleccionDeHotelButton = new javax.swing.JButton();
        hotelSeleccionadoLabel = new javax.swing.JLabel();
        menuClientePanelSlider = new diu.swe.habib.JPanelSlider.JPanelSlider();
        reservacionesPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        habitacionesDisponiblesTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fechaInDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fechaOutDateChooser = new com.toedter.calendar.JDateChooser();
        buscarHabitcionesDisponiblesButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cambioA_OpinionesButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        habitacionesA_ReservarTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        totalTextField = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        opinionesPanel = new javax.swing.JPanel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hoteles ");

        hotelesDeEmpresaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Direccion"
            }
        ));
        hotelesDeEmpresaTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(hotelesDeEmpresaTable);

        seleccionDeHotelButton.setText("Seleccionar");
        seleccionDeHotelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionDeHotelButtonActionPerformed(evt);
            }
        });

        hotelSeleccionadoLabel.setText("Hotel seleccionado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seleccionDeHotelButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hotelSeleccionadoLabel)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionDeHotelButton)
                .addGap(50, 50, 50)
                .addComponent(hotelSeleccionadoLabel)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jLabel2.setText("Reservaciones");

        jLabel3.setText("Habitaciones disponibles:");

        habitacionesDisponiblesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TPiso", "Tipo", "Numero de habitacion", "Costo por noche"
            }
        ));
        jScrollPane2.setViewportView(habitacionesDisponiblesTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jLabel4.setText("Calificacion y comentarios.");

        jLabel6.setText("Fecha check In:");

        jLabel7.setText("Fecha check out");

        buscarHabitcionesDisponiblesButton.setText("Buscar ");
        buscarHabitcionesDisponiblesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarHabitcionesDisponiblesButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Reservar");

        cambioA_OpinionesButton.setText("Cambiar a opiniones");
        cambioA_OpinionesButton.setFocusable(false);
        cambioA_OpinionesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cambioA_OpinionesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cambioA_OpinionesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioA_OpinionesButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Habitaciones a reservar:");

        habitacionesA_ReservarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Piso", "Tipo", "NumeroDeHabitacion", "Costo por noche", "Dias", "Costo total"
            }
        ));
        jScrollPane5.setViewportView(habitacionesA_ReservarTable);

        jButton1.setText("Calcular total");

        jLabel5.setText("Valoracion:");

        jButton7.setText("Usar habitacion");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Cancelar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reservacionesPanelLayout = new javax.swing.GroupLayout(reservacionesPanel);
        reservacionesPanel.setLayout(reservacionesPanelLayout);
        reservacionesPanelLayout.setHorizontalGroup(
            reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservacionesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservacionesPanelLayout.createSequentialGroup()
                        .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(reservacionesPanelLayout.createSequentialGroup()
                                .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(reservacionesPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(fechaInDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(39, 39, 39)
                                .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(reservacionesPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(fechaOutDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buscarHabitcionesDisponiblesButton)))
                                .addGap(0, 50, Short.MAX_VALUE))
                            .addGroup(reservacionesPanelLayout.createSequentialGroup()
                                .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton7)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(reservacionesPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(reservacionesPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reservacionesPanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel2)
                        .addGap(165, 165, 165)
                        .addComponent(cambioA_OpinionesButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(reservacionesPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservacionesPanelLayout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(reservacionesPanelLayout.createSequentialGroup()
                        .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(56, 56, 56))))
        );
        reservacionesPanelLayout.setVerticalGroup(
            reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservacionesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cambioA_OpinionesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fechaInDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(fechaOutDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buscarHabitcionesDisponiblesButton))
                .addGap(38, 38, 38)
                .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15))
                .addGap(36, 36, 36)
                .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservacionesPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8)))
                    .addGroup(reservacionesPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton7)))
                .addGap(34, 34, 34)
                .addGroup(reservacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(reservacionesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuClientePanelSlider.add(reservacionesPanel, "card2");

        jLabel8.setText("Fecha checkIn:");

        jLabel9.setText("Fecha checkOut");

        jButton3.setText("Revisar estancias");

        jLabel10.setText("Opiniones");

        jLabel11.setText("Si no indica fecha se mostraran todas las estancias que ha tenido.");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel12.setText("Alojamientos encontrados:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Ingrese aqui su comentario.");
        jScrollPane4.setViewportView(jTextArea1);

        jLabel14.setText("Puntuacion:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel13.setText("Calificacion y comentario:");

        jButton4.setText("Guardar opinion");

        jButton5.setText("Cancelar");

        jButton6.setText("Volver a reservaciones");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opinionesPanelLayout = new javax.swing.GroupLayout(opinionesPanel);
        opinionesPanel.setLayout(opinionesPanelLayout);
        opinionesPanelLayout.setHorizontalGroup(
            opinionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opinionesPanelLayout.createSequentialGroup()
                .addGroup(opinionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(opinionesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(opinionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(opinionesPanelLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(opinionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addGroup(opinionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(opinionesPanelLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addGroup(opinionesPanelLayout.createSequentialGroup()
                                    .addGroup(opinionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(opinionesPanelLayout.createSequentialGroup()
                                            .addGap(344, 344, 344)
                                            .addComponent(jLabel10))
                                        .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6))))
                        .addGroup(opinionesPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        opinionesPanelLayout.setVerticalGroup(
            opinionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opinionesPanelLayout.createSequentialGroup()
                .addGroup(opinionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opinionesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel11))
                    .addGroup(opinionesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6)))
                .addGap(18, 18, 18)
                .addGroup(opinionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton3)
                .addGap(45, 45, 45)
                .addGroup(opinionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(opinionesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(opinionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)))
        );

        menuClientePanelSlider.add(opinionesPanel, "card3");

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Cerrar Sesion");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cerrar Sesion y Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuClientePanelSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuClientePanelSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambioA_OpinionesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioA_OpinionesButtonActionPerformed
        this.menuClientePanelSlider.nextPanel(5, this.opinionesPanel, this.menuClientePanelSlider.left);
    }//GEN-LAST:event_cambioA_OpinionesButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.menuClientePanelSlider.nextPanel(5, this.reservacionesPanel, this.menuClientePanelSlider.left);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void buscarHabitcionesDisponiblesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarHabitcionesDisponiblesButtonActionPerformed
        Date tiempo1 = fechaInDateChooser.getDate();
        Date tiempo2 = fechaOutDateChooser.getDate();
        try {
            java.sql.Date fechaBaseDeDatos1 = new java.sql.Date(tiempo1.getTime());
            java.sql.Date fechaBaseDeDatos2 = new java.sql.Date(tiempo2.getTime());
            if (fechaBaseDeDatos1.toString().equals(fechaBaseDeDatos2.toString())) {
                JOptionPane.showMessageDialog(this, "La fecha de CheckIn no puede ser igual a la de check Out");
            } else if (fechaBaseDeDatos1.after(fechaBaseDeDatos2)) {
                JOptionPane.showMessageDialog(this, "La fecha de checkIn no puede ser mayor a la de checkOut");
            } else {
                BusquedaDeHabitaciones nuevaBusqueda = new BusquedaDeHabitaciones();
                if (this.hotelSeleccionado == null) {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un hotel");
                } else {
                    this.habitacionesDisponibles = nuevaBusqueda.buscarHabitacionesSinReservacion(fechaBaseDeDatos1, fechaBaseDeDatos2, this.hotelSeleccionado.getCodigoDeEmpresa());
                    DefaultTableModel miModelo = (DefaultTableModel) this.habitacionesDisponiblesTable.getModel();
                    for (Habitacion habitacion : this.habitacionesDisponibles) {
                        miModelo.addRow(new Object[]{habitacion.getPiso(), habitacion.getTipoDeHabitacion(), habitacion.getNumeroDeHabitacion(), habitacion.getCostoPorNoche()});
                    }
                    //Calcular dias de difirencia
                    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    this.diasDeAlojamiento = calculrDiasDeDiferencia(dateFormat.format(tiempo1), dateFormat.format(tiempo2));
                    JOptionPane.showMessageDialog(this, diasDeAlojamiento);

                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Existio un error al conectar con la base de datos");
        }

    }//GEN-LAST:event_buscarHabitcionesDisponiblesButtonActionPerformed

    private void seleccionDeHotelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionDeHotelButtonActionPerformed
        int hotelSeleccionado = this.hotelesDeEmpresaTable.getSelectedRow();
        if (hotelSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un hotel en la tabla superior");
        } else {
            DefaultTableModel miModelo = (DefaultTableModel) this.hotelesDeEmpresaTable.getModel();
            this.hotelSeleccionado = this.listaDeHoteles.get(hotelSeleccionado);
            this.hotelSeleccionadoLabel.setText("Hotel seleccionado:" + this.hotelSeleccionado.getNombreDeEmpresa());
        }
    }//GEN-LAST:event_seleccionDeHotelButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int numeroDeFila = this.habitacionesDisponiblesTable.getSelectedRow();
        if (numeroDeFila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una habitacion");
        } else {
            Habitacion hab = this.habitacionesDisponibles.get(numeroDeFila);
            this.habitacionesQueSeReservaran.add(this.habitacionesDisponibles.get(numeroDeFila));
            DefaultTableModel miModelo = (DefaultTableModel) this.habitacionesA_ReservarTable.getModel();
            //piso tipo numeroDeHabitacion CostoPorNoche Dias CosotTotal
            Double costoTotal = hab.getCostoPorNoche() * this.diasDeAlojamiento;
            miModelo.addRow(new Object[]{hab.getPiso(), hab.getTipoDeHabitacion(), hab.getNumeroDeHabitacion(), hab.getCostoPorNoche(), this.diasDeAlojamiento, costoTotal});
            this.habitacionesDisponibles.remove(numeroDeFila);
            miModelo = (DefaultTableModel) this.habitacionesDisponiblesTable.getModel();
            miModelo.removeRow(numeroDeFila);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int filaSeleccionada = this.habitacionesA_ReservarTable.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una habitacion");
        } else {
            this.habitacionesDisponibles.add(this.habitacionesQueSeReservaran.get(filaSeleccionada));
            DefaultTableModel miModelo = (DefaultTableModel) this.habitacionesDisponiblesTable.getModel();
            Habitacion habitacion=this.habitacionesDisponibles.get(this.habitacionesDisponibles.size()-1);
            miModelo.addRow(new Object[]{habitacion.getPiso(), habitacion.getTipoDeHabitacion(), habitacion.getNumeroDeHabitacion(), habitacion.getCostoPorNoche()});
            miModelo =(DefaultTableModel)this.habitacionesA_ReservarTable.getModel();
            miModelo.removeRow(filaSeleccionada);
            this.habitacionesQueSeReservaran.remove(filaSeleccionada);
        }
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarHabitcionesDisponiblesButton;
    private javax.swing.JButton cambioA_OpinionesButton;
    private com.toedter.calendar.JDateChooser fechaInDateChooser;
    private com.toedter.calendar.JDateChooser fechaOutDateChooser;
    private javax.swing.JTable habitacionesA_ReservarTable;
    private javax.swing.JTable habitacionesDisponiblesTable;
    private javax.swing.JLabel hotelSeleccionadoLabel;
    private javax.swing.JTable hotelesDeEmpresaTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private diu.swe.habib.JPanelSlider.JPanelSlider menuClientePanelSlider;
    private javax.swing.JPanel opinionesPanel;
    private javax.swing.JPanel reservacionesPanel;
    private javax.swing.JButton seleccionDeHotelButton;
    private javax.swing.JTextField totalTextField;
    // End of variables declaration//GEN-END:variables

    private void buscarHoteles() {
        BusquedaDeEmpresas nuevaBusqueda = new BusquedaDeEmpresas();
        DefaultTableModel miModelo = (DefaultTableModel) this.hotelesDeEmpresaTable.getModel();
        try {
            this.listaDeHoteles = nuevaBusqueda.buscarEmpresas("Hotel");
            for (Empresa hotel : listaDeHoteles) {
                miModelo.addRow(new Object[]{hotel.getNombreDeEmpresa(), hotel.getDireccionDeEmpresa()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos");
            Logger.getLogger(MenuParaClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public int calculrDiasDeDiferencia(String fechaInicio, String fechaFinal) {
        try {
            SimpleDateFormat nuevoFormato = new SimpleDateFormat("yyyy-MM-dd");
            Date fechaInicial = nuevoFormato.parse(fechaInicio);
            Date fechaFin = nuevoFormato.parse(fechaFinal);
            int dias = (int) ((fechaFin.getTime() - fechaInicial.getTime()) / 86400000);
            return dias;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Existio un error al darle formato a las fechas");
        }
        return 0;
    }

}
